[[redirects]]
  from = "/"
  to = "/public/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/driver"
  to = "/driver/index.html"
  status = 200

[[redirects]]
  from = "/partner"
  to = "/partner/index.html"
  status = 200

[[redirects]]
  from = "/apply"
  to = "/public/partner-apply.html"
  status = 200
